image: rwercker/base

stages:
  - basic
  - check

r-base-basic:
  stage: build
  script:
    - R -e "devtools::document()"
    - R -e "devtools::build('.','.')"
    - R -e "devtools::test()"
    - R -e "devtools::codecov()"
  artifacts:
    paths:
      - man/
      - NAMESPACE
      - praznik_*.tar.gz

r-base-check:
  stage: check
  script:
    - R CMD check --no-manual --no-build-vignettes praznik_*.tar.gz
  artifacts:
    paths:
      - praznik.Rcheck/

r-dev-check:
  stage: check
  before-script:
    - RD -e "install.packages('magrittr')"
    - RD -e "install.packages('testthat')"
  script:
    - RD CMD check --no-manual --no-build-vignettes praznik_*.tar.gz
  artifacts:
    paths:
      - praznik.Rcheck/
