image: rwercker/base

stages:
  - build
  - test
  - coverage

r-base-build:
  stage: build
  script:
    - R -e "devtools::document()"
    - R -e "devtools::load_all()"
    - R -e "devtools::build()"
  artifacts:
    paths:
      - man/
      - NAMESPACE
      - ../praznik_*.tar.gz

r-base-test:
  stage: test
  script:
    - R -e "devtools::test()"

r-base-cov:
  stage: coverage
  script:
    - R -e "covr::codecov()"
