image: registry.gitlab.com/mbq/arrch:latest

stages:
  - basic
  - check

r-base-basic:
  stage: basic
  script:
    - R -e "devtools::document()"
    - R -e "devtools::build('.','.')"
    - R -e "devtools::test()"
    - R -e "covr::codecov(quiet=FALSE,type='all')"
  artifacts:
    paths:
      - man/
      - NAMESPACE
      - praznik_*.tar.gz

r-base-check:
  stage: check
  script:
    - R CMD check praznik_*.tar.gz
  artifacts:
    paths:
      - praznik.Rcheck/

r-dev-check:
  stage: check
  allow_failure: true
  script:
    - RD CMD check praznik_*.tar.gz
  artifacts:
    paths:
      - praznik.Rcheck/
